### ISSUE TITLE
Improve description of LLOQ values

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/docs#221]
Here: https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/import-edit-observed-data#lloq

If the LLOQ column is used - what are the units? What format should the entries be in - "1" or "<1" or "1 ng/ml" or?

What should be the corresponding entry in the "Measurement" column, if there is an entry in "LLOQ" column? Emtpy? "BLOQ", "<1", or what?

**Comment by georgeDaskalakis** [comment]
@PavelBal I am not sure waht you mean with your last sentence: 
If the LLOQ comes from a column, in the Measurement column there should only be the measurement.

**Comment by PavelBal** [comment]
I think 🤔 I meant that lloq entries in the measurement column, like "<3", will not be considered if the values are already definitely in the lloq column

**Comment by georgeDaskalakis** [comment]
@PavelBal yes this is correct: If the LLOQ comes from a column, then entries in the measurement column that are of the form eg "<0.2" will be filtered out, since  the requirement is that all measurement values are numerical, and in this specific case the values are not, since the LLOQ comes from the column and the measurement column is not parsed for LLOQ values.

I have added this also to the description.
